services:
#    main_weather.example:
#        class: Main\WeatherBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    open_weather_api:
        class: Main\WeatherBundle\API\OpenWeatherAPI

    wunderground_api:
        class: Main\WeatherBundle\API\WundergroundAPI


    nfq.weather:
        class: Main\WeatherBundle\Helper\WeatherService
        arguments: [@open_weather_api]
